import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';
import Sidebar from './components/sidebar';
import Navbar from './components/navbar';

const inter = Inter({
  subsets: ['latin'],
  weight: ['200', '300', '400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={cn('antialiased bg-[#68746f0f]', inter.className)}>
        <div className='flex relative'>
          <Sidebar />
          <section className='w-[calc(100vw-230px)] absolute right-0 flex flex-col gap-4'>
            <Navbar />
            <main>{children}</main>
          </section>
        </div>
      </body>
    </html>
  );
}
